### ISSUE TITLE
[BUG] Received HTTP/0.9 when not allowed

### ISSUE THREAD

**Issue by fadiinho** [luisviniciuslv/PyForgeAPI#1]
I'm using the basic example from README
```python
from PyForgeAPI import Routes, Response, Request

routes = Routes(debug=True)

@routes.get("/")
async def home(_: Request, res: Response):
    res.json({"message": "Hi"}).status(200).send()


routes.run(application="Person API", host="localhost", port=3000)
```
When I try to CURL the url, this happens:
![image](https://user-images.githubusercontent.com/94945604/213897383-73c5e9bc-cc4d-4b54-b0da-e01e0046f246.png)
And when using a browser, I get `INVALID_HTTP_RESPONSE`.
On debug mode it only logs the request, no errors.

**Comment by Bielgomes** [comment]
What is your python version?

**Comment by fadiinho** [comment]
I'm using version 3.10.6

**Comment by luisviniciuslv** [comment]
try curl localhost:3000 -v --http1.1

**Comment by fadiinho** [comment]
Nothing changed with `curl localhost:3000 -v --http1.1`, but if I use `curl localhost:3000 -v --http0.9`, it works as expected. But `HTTP/0.9` is a old format

**Comment by Bielgomes** [comment]
The server only accepts HTTP 1.X requests, HTTP 0.9 is already obsolete! Take a look at your cURL is communicating

**Comment by Bielgomes** [comment]
> Nothing changed with `curl localhost:3000 -v --http1.1`, but if I use `curl localhost:3000 -v --http0.9`, it works as expected. But `HTTP/0.9` is a old format

Yep

**Comment by fadiinho** [comment]
The problem is that even on the browser I receive `HTTP_INVALID_RESPONSE`.
![image](https://user-images.githubusercontent.com/94945604/213898841-554a20de-a271-4d67-a1d7-2be362f3dc34.png)

**Comment by Bielgomes** [comment]
are you putting the url with http or with https?

**Comment by Bielgomes** [comment]
Try updating to PyForgeAPI version 1.3.0

**Comment by luisviniciuslv** [comment]
We have discovered the reason for this bug, it is due to our implementation of CORS, it will be fixed in the next update, a temporary solution is to use the CORS potion when defining the route using CORS, ```route = Routes().cors()```
