### ISSUE TITLE
[ENHACEMENT] Default host to `localhost` and port to `5000`

### ISSUE THREAD

**Issue by fadiinho** [luisviniciuslv/PyForgeAPI#2]
### Why?
Usually when developing an api locally we set  the host to `localhost`, so if we set the default to `localhost` it becomes more convenient.
And about the port it needs root privileges (on linux) to run on port 80, so same as the host, it becomes more convenient.
Usually the libraries to build apis defaults it to `localhost` and some port higher than 1024, flask for example [here](https://github.com/pallets/flask/blob/ef85270d9ada6d9b25beabb4602047fc91eef2f9/src/flask/app.py#L1173)

**Comment by Bielgomes** [comment]
We appreciate your feedback and understand your vision! We saw that you opened a pull request, but it needs to exchange a check! before it checked if host was none to get the default ip, now it has to be "0.0.0.0"
